source 'https://rubygems.org'

gem 'rails', '5.0.0.rc1'
gem 'github_api'
gem 'dotenv-rails'
gem 'mongoid', git: 'https://github.com/mongodb/mongoid.git'
gem 'bson_ext'
gem 'sidekiq'
gem 'clockwork'
gem 'pry'
gem 'puma'
gem 'redis'
gem 'foreman'
gem 'rack-cors', require: 'rack/cors'
gem 'mina'
