default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: github_broadcast_development

production:
  <<: *default
  database: github_broadcast_production
  pool: 100
